### ISSUE TITLE
처음 npm start o 할때 오류

### ISSUE THREAD

**Issue by hoonhoons** [pfldy2850/yscec-crawler2#1]
처음에 npm start o를 한 다음
아이디, 이메일 정보등을 입력한 다음 엔터를 누르면 다음과 같은 오류가 발생합니다.

```
* CREATE YSCEC account info file: SUCCEEDED; secret.json
-------------------------------------------------------
* START LOGIN to YSCEC
└ LOGIN PROCESS 1/8 : SUCCEEDED
└ LOGIN PROCESS 2/8 : SUCCEEDED
└ LOGIN PROCESS 3/8 : SUCCEEDED
└ LOGIN PROCESS 4/8 : SUCCEEDED
└ LOGIN PROCESS 5/8 : SUCCEEDED
└ LOGIN PROCESS 6/8 : SUCCEEDED
└ LOGIN PROCESS 7/8 : FAILED Error: options.uri is a required argument
    at Request.init (/home/hoon/yscec-crawler2/node_modules/request/request.js:234:31)
    at new Request (/home/hoon/yscec-crawler2/node_modules/request/request.js:130:8)
    at request (/home/hoon/yscec-crawler2/node_modules/request/index.js:54:10)
    at Promise (/home/hoon/yscec-crawler2/crawler.js:238:5)
    at Promise (<anonymous>)
    at loginProcess2 (/home/hoon/yscec-crawler2/crawler.js:237:10)
    at Object.exports.run (/home/hoon/yscec-crawler2/crawler.js:580:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
└ LOGIN PROCESS 7/8 : SUCCEEDED
```

다시 한 번 npm start o를 하니 이 에러 없이 실행이 잘 되었습니다.

**Comment by pfldy2850** [comment]
감사합니다.

이 에러는 LOGIN PROCESS 6/8 에서 중간에 문제(인터넷 연결… 등)가 있어서 7/8에서 에러가 난 것 같습니다.

다음에 실행을 하니 잘 되었다고 하니, 정상 로직에서의 문제는 없는 것 같고, 예외처리와 에러 익스프레션 처리를 좀 더 하도록 하겠습니다.
